### ISSUE TITLE
Error while loading dem in windows

### ISSUE THREAD

**Issue by tproduit** [tproduit/pic2map#7]
Dem stored in C:\Users\sasgin.BRIG\Documents\QGIS\my_qgis_projects\data raise error
Dem stored in C:\\data is ok

**Comment by frpin33** [comment]
The problem is from the dot in sasgin.BRIG. Look in Pic2Map.py in the function startSequence around the line 110-120, The code make a string split with a dot, so the path is cut in 3 part instead of 2. If you switch the 1 to -1 at line 119 it will always check for the last string of the split which should always be the type of file.

**Comment by sgindraux** [comment]
Ok that was no luck then ;-) thanks for looking at it!
