### ISSUE TITLE
Not 100% working on QGIS 3.4.x LTR (3.8) & Xubuntu 18.04

### ISSUE THREAD

**Issue by mrksgit** [tproduit/pic2map#8]
Hi,
I'm using QGIS 3.4.9 and tried to use Pic2Map. I installed the required python2/python3/OpenGL/QT4/QT5 modules but still it doesn't seem to work 100% correct. Neither in the latest stable release 3.8, nor in the current LTR (3.4.9).

I tried the testdata set first. Loading the Points & Pose work properly. 3D-Preview works like a charme, so it shouldn't be a "Linux-OpenGL thing" per se as I thought in the first place.

![overview](https://user-images.githubusercontent.com/13807880/62478832-93dc1a00-b79b-11e9-8c01-35afeed1eba0.png)

But the final "Orthorectification" doesn't produce a usable output in the preview and exporting it as a raster image is just resulting in a black picture.

![ortho-fail](https://user-images.githubusercontent.com/13807880/62478837-976fa100-b79b-11e9-940e-ae49142fa30c.png)

Did I missed something? What more information do you need from the system used? You have an idea, what might be wrong? 

Thank you

**Comment by frpin33** [comment]
Orthorectification only give you information gatter from the picture, it doesn't compute anything to fill the missing pixel. So when the information is missing, it but a black dot. You can't know what is behing the mountain because the picture doesn't show it. Basically, each pixel from the picture is use and put on the associate coordonate of your DEM. The output is mostly use to put on top of your DEM layer. The result would probably be better if the picture was taken from the sky since you will lose no information from object behind a mountain for example.

Edit : It seems I red a bit too fast your question, sorry abut that. 

To complete the save you need to select a part of the window, it should look like this 

![image](https://user-images.githubusercontent.com/22438251/62553901-3056f880-b83e-11e9-8693-12edb2bd02f9.png)

![image](https://user-images.githubusercontent.com/22438251/62555013-2e8e3480-b840-11e9-94e1-a4081c5cf3b5.png)


The purple rectangle would be save as a tif. To create the purple rectangle is a bit tricky since you can only start from the top left corner. So to draw the rectangle, when you click on the screen always go down and to the right and it should work.

**Comment by tproduit** [comment]
If I remember well, in the orthorectification window, you have to draw a rectangle around the area that you want to extract and clic `save raster`.

**Comment by mrksgit** [comment]
Thank you. Indeed. It was a typical case of RTFM :-) I misunderstood the actual scheme/scope of the orthorectification function. But still there seems a strange behaviour with QGIS 3.8 and point symbology of point vectors. But I'm going to open a new issue for that.
